version: "3"

services:
  playwright-behind-vpn:
    build: ./
    image: ${REGISTRY_URL}/playwright-behind-vpn
    cap_add:
      - NET_ADMIN
    environment:
      #PROVIDER: ${PROVIDER}
      SURFSHARK_USER: ${SURFSHARK_USER}
      SURFSHARK_PASSWORD: ${SURFSHARK_PASSWORD}
      PUREVPN_USER: ${PUREVPN_USER}
      PUREVPN_PASSWORD: ${PUREVPN_PASSWORD}
    networks:
      - default
  #enter curl container via "docker exec -it" and check ip via "curl ifconfig.me"
  nginx:
    build: ./nginx
    image: ${REGISTRY_URL}/playwright-behind-vpn-nginx
    ports:
      - "4000:80"
    networks:
      - default
