version: "3"

services:
  scraping-api-agent:
    build: ./
    #image: mucks/scraping-api-agent:latest
    cap_add:
      - NET_ADMIN
    environment:
      VPN_PROVIDER: ${VPN_PROVIDER}
      VPN_PROVIDER_USERNAME: ${VPN_PROVIDER_USERNAME}
      VPN_PROVIDER_PASSWORD: ${VPN_PROVIDER_PASSWORD}
    networks:
      - default
  #enter curl container via "docker exec -it" and check ip via "curl ifconfig.me"
  nginx:
    build: ./nginx
    ports:
      - "4000:80"
    networks:
      - default
