version: "3"

services:
  scraping-api-agent:
    build: ./
    image: mucks/scraping-api-agent
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      #PROVIDER: ${PROVIDER}
      SURFSHARK_USER: ${SURFSHARK_USER}
      SURFSHARK_PASSWORD: ${SURFSHARK_PASSWORD}
      PUREVPN_USER: ${PUREVPN_USER}
      PUREVPN_PASSWORD: ${PUREVPN_PASSWORD}
    networks:
      - default
  #enter curl container via "docker exec -it" and check ip via "curl ifconfig.me"
  nginx:
    build: ./nginx
    ports:
      - "4000:80"
    networks:
      - default
