apiVersion: v1
kind: Pod
metadata:
  name: scraping-api-agent
  namespace: scraping-api
  labels:
    name: scraping-api-agent
spec:
  containers:
    - name: scraping-api-agent
      image: mucks/scraping-api-agent:0.1-beta-alpine
      env:
        - name: SURFSHARK_USER
          valueFrom:
            configMapKeyRef:
              name: scraping-api-agent-config-secret
              key: SURFSHARK_USER
        - name: SURFSHARK_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: scraping-api-agent-config-secret
              key: SURFSHARK_PASSWORD
      # resources:
      #   limits:
      #     memory: "300Mi"
      #     cpu: "100m"
      ports:
        - containerPort: 4000
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - SYS_ADMIN
