apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scraping-api-agent-pvc
  namespace: scraping-api
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
