apiVersion: v1
kind: Pod
metadata:
  name: scraping-api-agent
  namespace: scraping-api
  labels:
    name: scraping-api-agent
spec:
  dnsConfig:
    nameservers:
      - 1.1.1.1
      - 1.0.0.1
  containers:
    - name: scraping-api-agent
      image: mucks/scraping-api-agent:0.1-beta-alpine
      env:
        - name: SURFSHARK_USER
          valueFrom:
            configMapKeyRef:
              name: scraping-api-agent-config-secret
              key: SURFSHARK_USER
        - name: SURFSHARK_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: scraping-api-agent-config-secret
              key: SURFSHARK_PASSWORD
      resources:
        limits:
          memory: "512Mi"
          cpu: "250m"
      ports:
        - containerPort: 4000
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - SYS_ADMIN
